# Generated by Django 3.1.7 on 2021-03-20 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(default='', max_length=100)),
                ('field_of_project', models.CharField(default='', max_length=100)),
                ('duration', models.CharField(max_length=20)),
                ('about', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('stipend', models.CharField(max_length=100)),
                ('skills_required', models.CharField(max_length=500)),
                ('no_of_vaccancy', models.PositiveIntegerField()),
                ('perks', models.CharField(max_length=100)),
                ('apply_by', models.DateField(default='2000-01-01', help_text='YYYY-MM-DD Format should be followed for the date.')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInternship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup', models.CharField(default='', max_length=100)),
                ('duration', models.CharField(max_length=20)),
                ('stipend', models.CharField(max_length=100)),
                ('apply_by', models.DateField(default='2000-01-01', help_text='YYYY-MM-DD Format should be followed for the date.')),
                ('link', models.URLField(default='', help_text='Add link for application. ')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='', max_length=1200)),
                ('resume', models.URLField(default='', help_text='Add the drive link to your resume.')),
                ('applied_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='intern', to=settings.AUTH_USER_MODEL)),
                ('internship', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='internship.project')),
            ],
        ),
    ]
