# Generated by Django 3.0.7 on 2021-03-20 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinternship',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_student': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentinternship',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
