# Generated by Django 3.0.7 on 2021-03-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yrbranch',
            name='branch',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='yrbranch',
            name='year',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
