# Generated by Django 3.0.7 on 2021-03-20 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210320_2107'),
        ('user', '0002_auto_20210320_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_company',
        ),
        migrations.AddField(
            model_name='user',
            name='yr_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.YrBranch'),
        ),
    ]
