# Generated by Django 3.1.7 on 2021-03-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210320_2107'),
        ('user', '0003_auto_20210320_2044'),
    ]

    operations = [
    ]
