# Generated by Django 3.1.7 on 2021-03-20 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_merge_20210320_1721'),
        ('user', '0004_merge_20210320_2236'),
    ]

    operations = [
    ]
