# Generated by Django 3.1.7 on 2021-03-20 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210321_0145'),
        ('user', '0005_merge_20210321_0324'),
    ]

    operations = [
    ]
