# Generated by Django 3.0.7 on 2021-03-20 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_merge_20210320_1721'),
        ('user', '0005_auto_20210321_0145'),
    ]

    operations = [
    ]
