# Generated by Django 3.0.7 on 2021-03-20 21:55

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_merge_20210321_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Add country code before the contact no.', max_length=128, null=True, region=None),
        ),
    ]
