# Generated by Django 3.1.7 on 2021-03-21 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_username'),
        ('user', '0008_user_is_company'),
    ]

    operations = [
    ]
